### ISSUE TITLE
litmus does not sent Content-Type: application/xml with PROPFIND and PROPPATCH request bodies

### ISSUE THREAD

**Issue by gstrauss** [notroj/litmus#5]
**Describe the bug**
litmus `props` does not sent `Content-Type: application/xml` with `PROPFIND` and `PROPPATCH` non-zero request bodies

**Environment**
litmus git master HEAD
 - litmus version: 0.14
 - neon version: (submodule status differs from litmus `NEWS` for litmus 0.14)
 ```
$ git submodule status
 258301b2fb85398ed478386faf220228457ec3b5 neon (0.32.3-29-g258301b)
```
 - OS: Fedora 37
 - SSL library version:
 ```
$ openssl version
OpenSSL 3.0.5 5 Jul 2022 (Library: OpenSSL 3.0.5 5 Jul 2022)
```

**To Reproduce**
[lighttpd](https://lighttpd.net/) [mod_webdav](https://wiki.lighttpd.net/mod_webdav) returns 415 Unsupported Media Type for litmus tests sending `PROPFIND` or `PROPPATCH` requests with a non-zero request body when litmus is run against lighttpd mod_webdav.  The tests pass if I disable lighttpd mod_webdav strict enforcement that request body to `PROPFIND` and `PROPPATCH` with non-zero length must have `Content-Type: application/xml` or `Content-Type: text/xml`.

[rfc4918#section-8.2](https://datatracker.ietf.org/doc/html/rfc4918#section-8.2)
```
   When XML is used for a request or response body, the Content-Type
   type SHOULD be application/xml.  Implementations MUST accept both
   text/xml and application/xml in request and response bodies.  Use of
   text/xml is deprecated.
```
While the wording could be a bit more explicit, I read the above as implying that one of `Content-Type: application/xml` or `Content-Type: text/xml` is required, or at least that the server is allowed to reject anything other than the two types that were stated as types the server MUST accept for those XML request or response bodies.

Are you aware of any WebDAV clients (besides litmus) which omit `Content-Type` in `PROPFIND` or `PROPPATCH` requests containing a non-zero request body?  Do you think that I should downgrade lighttpd mod_webdav strict enforcement and "assume" that the request body is `Content-Type: application/xml` if `Content-Type` is not provided?

**Debugging output**
```
 2. propfind_invalid...... FAIL (PROPFIND with non-well-formed XML request body got 415 response not 400)
 3. propfind_invalid2..... FAIL (PROPFIND with invalid namespace declaration in body (see FAQ) got 415 response not 400)
15. propnullns............ FAIL (PROPPATCH of property with null namespace (see FAQ))
16. propget............... FAIL (No value given for property {}nonamespace)
17. prophighunicode....... FAIL (PROPPATCH of property with high unicode value)
18. propget............... FAIL (No value given for property {http://example.com/neon/litmus/}high-unicode)
19. propremoveset......... FAIL (PROPPATCH remove then set)
20. propget............... FAIL (No value given for property {http://example.com/neon/litmus/}removeset)
21. propsetremove......... FAIL (PROPPATCH remove then set)
23. propvalnspace......... FAIL (PROPPATCH of property with value defining namespace)
```

**Comment by notroj** [comment]
Oh, that's really interesting, thanks for the report @gstrauss 

Yes, I agree with your interpretation of the wording in 4918. It might be worth opening an erratum for the RFC to clarify it.

If you've not seen this with any real clients then I wouldn't relax the server code, no, this is just a bug in the tests.  AFAICT neon does properly set the C-T internally for `ne_proppatch()` etc, it's just the custom `PROPPATCH` handling in litmus that are buggy here.

**Comment by notroj** [comment]
If you can retest with 8c5c718aa7497eac63bf494521813b740701fe7d please reopen & let me know if there's still an issue here?

**Comment by gstrauss** [comment]
`props` now works for me without those errors.  Thanks!

Aside: lighttpd mod_webdav uses libxml2, which detects and warns about certain namespace errors, but does not necessarily throw an error (or didn't provide an option to do so when I last looked in 2016), so lighttpd mod_webdav fails `props` test `propfind_invalid2` for that reason.  litmus is correct since the RFC says that implementations MUST fail for that.

lighttpd mod_webdav passes all the rest of the `litmus` tests.  (The upcoming release of lighttpd fixes the recently updated `basic` test `put_no_parent`, as lighttpd was previously returning 500 instead of 409 for that.)

Cheers

**Comment by notroj** [comment]
Great, thanks a lot!
