### ISSUE TITLE
Golang webdav COPY lock

### ISSUE THREAD

**Issue by stokito** [notroj/litmus#9]
In Golang webdav implementation I found this 

> Section 7.5.1 says that a COPY only needs to lock the destination,
> not both destination and source. Strictly speaking, this is racy,
> even though a COPY doesn't modify the source, if a concurrent
> operation modifies the source. However, the litmus test explicitly
> checks that COPYing a locked-by-another source is OK.

https://github.com/golang/net/blob/9f24bb44e6dfa4fadbda1cd143a46d288ba89ae5/webdav/webdav.go#L356

Can you please clarify it this is expected or maybe the Litmus test can be improved

**Comment by notroj** [comment]
I think this is fairly clear in the RFC, e.g. in RFC 4918 https://www.rfc-editor.org/rfc/rfc4918#section-7

```
   Of the methods defined in HTTP and WebDAV, PUT, POST, PROPPATCH,
   LOCK, UNLOCK, MOVE, COPY (for the destination resource), DELETE, and
   MKCOL are affected by write locks.  All other HTTP/WebDAV methods
   defined so far -- GET in particular -- function independently of a
   write lock.
```

thus a write lock does **not** affect the source resource of a COPY. So it is reasonable for `litmus` to test that behaviour. Does that make sense?

FWIW I agree with the comment, it might be racy, but a user-agent could use a `Depth: 1` or `Depth: infinity` lock on the collection if required to avoid such races.

**Comment by notroj** [comment]
This specific case is also used an example in https://www.rfc-editor.org/rfc/rfc4918#section-7.5.1

**Comment by stokito** [comment]
thank you, now it's clear
